/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CashRegister;
import Model.Employee;
import Repositories.CashRegisterRepository;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author georgeborsato
 */
public class ViewDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ViewDashboard
     */
    
    private Employee employee;
    private CashRegister cashRegister;
    private CashRegisterRepository cashRegisterRepostiry;
   
    
    public ViewDashboard(Employee employee) {
        initComponents();
        this.jUserLogin.setText(employee.getName());
        this.employee = employee;
        System.out.println(employee.getTypeEmployee());
        this.cashRegisterRepostiry = new CashRegisterRepository();
        this.cashRegister = this.cashRegisterRepostiry.isOpen();
    }

    private ViewDashboard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jHeader = new javax.swing.JPanel();
        jButtonHandleSutdy = new javax.swing.JPanel();
        iconStudy = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonHandleEmployee = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        iconEmployee = new javax.swing.JLabel();
        jButtonHandlePersonal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonHandleReport = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonHandleExpense = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonHandleProduct = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jIconProduct = new javax.swing.JLabel();
        jButtonHandleCloseSystem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jIconClose = new javax.swing.JLabel();
        jAside = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jUserLogin = new javax.swing.JLabel();
        jMainContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jHandleRegistration = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jHandleSellProduct = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jHandleOpenCaixa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jHandleCloseCashRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHeader.setBackground(new java.awt.Color(1, 58, 99));

        jButtonHandleSutdy.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleSutdy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHandleSutdy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleSutdyMouseClicked(evt);
            }
        });

        iconStudy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cadastro_aluno.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(243, 243, 243));
        jLabel11.setText("ALUNOS");

        javax.swing.GroupLayout jButtonHandleSutdyLayout = new javax.swing.GroupLayout(jButtonHandleSutdy);
        jButtonHandleSutdy.setLayout(jButtonHandleSutdyLayout);
        jButtonHandleSutdyLayout.setHorizontalGroup(
            jButtonHandleSutdyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleSutdyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconStudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleSutdyLayout.setVerticalGroup(
            jButtonHandleSutdyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleSutdyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonHandleSutdyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconStudy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonHandleEmployee.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHandleEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleEmployeeMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(243, 243, 243));
        jLabel8.setText("FUNCIONÁRIOS");

        iconEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/funcionarios-32px.png"))); // NOI18N

        javax.swing.GroupLayout jButtonHandleEmployeeLayout = new javax.swing.GroupLayout(jButtonHandleEmployee);
        jButtonHandleEmployee.setLayout(jButtonHandleEmployeeLayout);
        jButtonHandleEmployeeLayout.setHorizontalGroup(
            jButtonHandleEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonHandleEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleEmployeeLayout.setVerticalGroup(
            jButtonHandleEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonHandleEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonHandleEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonHandlePersonal.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandlePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandlePersonalMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 243, 243));
        jLabel5.setText("PERSONAIS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/personal-32px.png"))); // NOI18N

        javax.swing.GroupLayout jButtonHandlePersonalLayout = new javax.swing.GroupLayout(jButtonHandlePersonal);
        jButtonHandlePersonal.setLayout(jButtonHandlePersonalLayout);
        jButtonHandlePersonalLayout.setHorizontalGroup(
            jButtonHandlePersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonHandlePersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandlePersonalLayout.setVerticalGroup(
            jButtonHandlePersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandlePersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonHandlePersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonHandlePersonalLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonHandleReport.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleReportMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 243, 243));
        jLabel6.setText("RELATÓRIOS");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/relatorio-32px.png"))); // NOI18N

        javax.swing.GroupLayout jButtonHandleReportLayout = new javax.swing.GroupLayout(jButtonHandleReport);
        jButtonHandleReport.setLayout(jButtonHandleReportLayout);
        jButtonHandleReportLayout.setHorizontalGroup(
            jButtonHandleReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonHandleReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleReportLayout.setVerticalGroup(
            jButtonHandleReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonHandleReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jButtonHandleReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jButtonHandleExpense.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHandleExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleExpenseMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/despesas_32px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(243, 243, 243));
        jLabel7.setText("DESPESAS");

        javax.swing.GroupLayout jButtonHandleExpenseLayout = new javax.swing.GroupLayout(jButtonHandleExpense);
        jButtonHandleExpense.setLayout(jButtonHandleExpenseLayout);
        jButtonHandleExpenseLayout.setHorizontalGroup(
            jButtonHandleExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleExpenseLayout.setVerticalGroup(
            jButtonHandleExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleExpenseLayout.createSequentialGroup()
                .addGroup(jButtonHandleExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonHandleExpenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jButtonHandleExpenseLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonHandleProduct.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHandleProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleProductMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(243, 243, 243));
        jLabel12.setText("PRODUTOS");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jIconProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/produtos_32px.png"))); // NOI18N

        javax.swing.GroupLayout jButtonHandleProductLayout = new javax.swing.GroupLayout(jButtonHandleProduct);
        jButtonHandleProduct.setLayout(jButtonHandleProductLayout);
        jButtonHandleProductLayout.setHorizontalGroup(
            jButtonHandleProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIconProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleProductLayout.setVerticalGroup(
            jButtonHandleProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonHandleProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jIconProduct))
                .addContainerGap())
        );

        jButtonHandleCloseSystem.setBackground(new java.awt.Color(1, 38, 74));
        jButtonHandleCloseSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHandleCloseSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHandleCloseSystemMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(243, 243, 243));
        jLabel13.setText("FECHAR SISTEMA");

        jIconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sair_32px.png"))); // NOI18N

        javax.swing.GroupLayout jButtonHandleCloseSystemLayout = new javax.swing.GroupLayout(jButtonHandleCloseSystem);
        jButtonHandleCloseSystem.setLayout(jButtonHandleCloseSystemLayout);
        jButtonHandleCloseSystemLayout.setHorizontalGroup(
            jButtonHandleCloseSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleCloseSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIconClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtonHandleCloseSystemLayout.setVerticalGroup(
            jButtonHandleCloseSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonHandleCloseSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonHandleCloseSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jIconClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout jHeaderLayout = new javax.swing.GroupLayout(jHeader);
        jHeader.setLayout(jHeaderLayout);
        jHeaderLayout.setHorizontalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonHandleSutdy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandleEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandlePersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandleReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandleExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandleProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHandleCloseSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHeaderLayout.setVerticalGroup(
            jHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeaderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButtonHandleSutdy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandleEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandlePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandleReport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandleExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHandleCloseSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jAside.setBackground(new java.awt.Color(97, 165, 194));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/man.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 243, 243));
        jLabel4.setText("Sistema de Controle SCAS");

        jUserLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jUserLogin.setForeground(new java.awt.Color(243, 243, 243));

        javax.swing.GroupLayout jAsideLayout = new javax.swing.GroupLayout(jAside);
        jAside.setLayout(jAsideLayout);
        jAsideLayout.setHorizontalGroup(
            jAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jUserLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );
        jAsideLayout.setVerticalGroup(
            jAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAsideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMainContent.setBackground(new java.awt.Color(222, 226, 230));

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));

        jPanel9.setBackground(new java.awt.Color(152, 193, 217));

        jHandleRegistration.setBackground(new java.awt.Color(152, 193, 217));
        jHandleRegistration.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jHandleRegistration.setForeground(new java.awt.Color(255, 255, 255));
        jHandleRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/avatar_study.png"))); // NOI18N
        jHandleRegistration.setText(" REALIZAR MATRICULAS");
        jHandleRegistration.setBorder(null);
        jHandleRegistration.setBorderPainted(false);
        jHandleRegistration.setContentAreaFilled(false);
        jHandleRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jHandleRegistration.setFocusPainted(false);
        jHandleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHandleRegistrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(61, 90, 128));

        jHandleSellProduct.setBackground(new java.awt.Color(61, 90, 128));
        jHandleSellProduct.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jHandleSellProduct.setForeground(new java.awt.Color(255, 255, 255));
        jHandleSellProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/carrinho.png"))); // NOI18N
        jHandleSellProduct.setText("VENDA DE PRODUTOS");
        jHandleSellProduct.setBorder(null);
        jHandleSellProduct.setBorderPainted(false);
        jHandleSellProduct.setContentAreaFilled(false);
        jHandleSellProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jHandleSellProduct.setFocusPainted(false);
        jHandleSellProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHandleSellProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleSellProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleSellProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(224, 159, 62));

        jHandleOpenCaixa.setBackground(new java.awt.Color(224, 159, 62));
        jHandleOpenCaixa.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jHandleOpenCaixa.setForeground(new java.awt.Color(255, 255, 255));
        jHandleOpenCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/money 1.png"))); // NOI18N
        jHandleOpenCaixa.setText("ABERTURA DE  CAIXA");
        jHandleOpenCaixa.setBorder(null);
        jHandleOpenCaixa.setBorderPainted(false);
        jHandleOpenCaixa.setContentAreaFilled(false);
        jHandleOpenCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jHandleOpenCaixa.setFocusPainted(false);
        jHandleOpenCaixa.setFocusable(false);
        jHandleOpenCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHandleOpenCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleOpenCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHandleOpenCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(233, 236, 239));
        jSeparator1.setForeground(new java.awt.Color(233, 236, 239));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 143, 175));
        jLabel1.setText("Seja bem vindo ao SCAS");

        jPanel2.setBackground(new java.awt.Color(61, 90, 128));

        jHandleCloseCashRegister.setBackground(new java.awt.Color(61, 90, 128));
        jHandleCloseCashRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jHandleCloseCashRegister.setForeground(new java.awt.Color(243, 243, 243));
        jHandleCloseCashRegister.setText("FECHAR CAIXA");
        jHandleCloseCashRegister.setBorder(null);
        jHandleCloseCashRegister.setBorderPainted(false);
        jHandleCloseCashRegister.setContentAreaFilled(false);
        jHandleCloseCashRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jHandleCloseCashRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHandleCloseCashRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jHandleCloseCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHandleCloseCashRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(563, 563, 563))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jMainContentLayout = new javax.swing.GroupLayout(jMainContent);
        jMainContent.setLayout(jMainContentLayout);
        jMainContentLayout.setHorizontalGroup(
            jMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainContentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jMainContentLayout.setVerticalGroup(
            jMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainContentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jAside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHandleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHandleRegistrationActionPerformed
        
        if(verifyCashRegister(this.cashRegister)){
            JOptionPane.showMessageDialog(null, "Por favor, abrir o caixa Primeiro", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            ViewCadastreRegister cadastreRegister = new ViewCadastreRegister(null, true, cashRegister, employee);
            cadastreRegister.setVisible(true);
        }
    }//GEN-LAST:event_jHandleRegistrationActionPerformed

    private void jHandleSellProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHandleSellProductActionPerformed
       
        
        if(verifyCashRegister(this.cashRegister)){
            JOptionPane.showMessageDialog(null, "Por favor, abrir o caixa Primeiro", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println("Vender produto");
            ViewSellProduct viewSellProduct = new ViewSellProduct(null, true, cashRegister);
            viewSellProduct.setVisible(true);
        }
      
    }//GEN-LAST:event_jHandleSellProductActionPerformed
    
    private void jHandleOpenCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHandleOpenCaixaActionPerformed
        System.out.println("Abrir Caixa");
        this.cashRegister = new CashRegister();
        ViewOpenCashRegister viewOpenCashRegister = new ViewOpenCashRegister(null, true, cashRegister);
        viewOpenCashRegister.setVisible(true);
        System.out.println(this.cashRegister.getDateCashRegister());
    }//GEN-LAST:event_jHandleOpenCaixaActionPerformed

    private void jButtonHandleEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleEmployeeMouseClicked
        ViewEmployee viewEmployee = new ViewEmployee(null, true);
        viewEmployee.setVisible(true);
    }//GEN-LAST:event_jButtonHandleEmployeeMouseClicked

    private void jButtonHandleSutdyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleSutdyMouseClicked
        ViewSectionStudy sectionStudy = new ViewSectionStudy(null, true);
        sectionStudy.setVisible(true);
    }//GEN-LAST:event_jButtonHandleSutdyMouseClicked

    private void jButtonHandlePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandlePersonalMouseClicked
        ViewPersonal viewPersonal = new ViewPersonal(null, true);
        viewPersonal.setVisible(true);
    }//GEN-LAST:event_jButtonHandlePersonalMouseClicked

    private void jButtonHandleReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleReportMouseClicked
        
        
        ViewReport viewReport = new ViewReport(null, true);
        viewReport.setVisible(true);
    }//GEN-LAST:event_jButtonHandleReportMouseClicked

    private void jButtonHandleExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleExpenseMouseClicked
          
           
        if(verifyCashRegister(this.cashRegister) || verifyCashRegisterClose(this.cashRegister)){
            JOptionPane.showMessageDialog(null, "Por favor, abrir o caixa Primeiro", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            ViewExpense viewExpense = new ViewExpense(null, true, cashRegister);
            viewExpense.setVisible(true);
        }
    }//GEN-LAST:event_jButtonHandleExpenseMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButtonHandleProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleProductMouseClicked
        ViewProduct viewProduct = new ViewProduct(null, true);
        viewProduct.setVisible(true);
    }//GEN-LAST:event_jButtonHandleProductMouseClicked

    private void jButtonHandleCloseSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHandleCloseSystemMouseClicked
        if(this.cashRegister.getClosingValue() == 0){
              JOptionPane.showMessageDialog(null, "Por favor, fechar caixa primeiro", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            setVisible(false);
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonHandleCloseSystemMouseClicked

    private void jHandleCloseCashRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHandleCloseCashRegisterActionPerformed
        Double valueInput = this.cashRegister.getInputValue();
        Double valueOutput = this.cashRegister.getOutputValue();
        Double valueOpen = this.cashRegister.getApertureValue();
       
        Double valueClose = (valueInput + valueOutput) - valueOpen;
        
        try{
            this.cashRegister.setClosingValue(valueClose);
            this.cashRegisterRepostiry.update(cashRegister);
            JOptionPane.showMessageDialog(null, "Caixa fechado com sucesso: " + valueClose + " reais");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o caixa", "Alert", JOptionPane.ERROR);
        }
        
    }//GEN-LAST:event_jHandleCloseCashRegisterActionPerformed
    
    
    private Boolean verifyCashRegisterClose(CashRegister cashRegister){
        if(this.cashRegister.getClosingValue() > 0){
            System.out.println("caixa fechado");
            return true;
        }else{
            
            return false;
        }
    }
    
    private Boolean verifyCashRegister(CashRegister cashRegister){
        if(this.cashRegister == null){
            return true;
        }else{
            System.out.println("caixa aberto");
             return false;
        }
    }
    
    
    /*private void VerifyCash(){
        
        try{
            CashRegister c = this.cashRegisterRepostiry.isOpen();
            System.out.println(c.toString());
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }*/
    
    private void block(){
        if(verifyCashRegister(cashRegister)){
            jHandleRegistration.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconEmployee;
    private javax.swing.JLabel iconStudy;
    private javax.swing.JPanel jAside;
    private javax.swing.JPanel jButtonHandleCloseSystem;
    private javax.swing.JPanel jButtonHandleEmployee;
    private javax.swing.JPanel jButtonHandleExpense;
    private javax.swing.JPanel jButtonHandlePersonal;
    private javax.swing.JPanel jButtonHandleProduct;
    private javax.swing.JPanel jButtonHandleReport;
    private javax.swing.JPanel jButtonHandleSutdy;
    private javax.swing.JButton jHandleCloseCashRegister;
    private javax.swing.JButton jHandleOpenCaixa;
    private javax.swing.JButton jHandleRegistration;
    private javax.swing.JButton jHandleSellProduct;
    private javax.swing.JPanel jHeader;
    private javax.swing.JLabel jIconClose;
    private javax.swing.JLabel jIconProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMainContent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jUserLogin;
    // End of variables declaration//GEN-END:variables
}
